apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burnham-ingress
  namespace: team-burnham
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: echoserver.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port: 
              number: 80
